# © 2026 Solvos Consultoría Informática (<http://www.solvos.es>)
# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html

import base64
import logging

from odoo import _, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class _DiscardTemporaryPicking(Exception):
    """ Internal exception used only to force the exit of the
    `with self.env.cr.savepoint():` block once we already have the PDF bytes
    in memory, so that the temporary picking created within that savepoint
    is undone and never persisted."""


class LogisticsSchedule(models.Model):
    _name = 'logistics.schedule'
    _inherit = ['logistics.schedule', 'deca.document.mixin']

    deca_driver_id = fields.Many2one(
        'res.partner',
        string="Driver",
    )
    deca_signature = fields.Binary(
        string="DeCA Signature",
        copy=False,
        help="Signature required to generate the DeCA document.",
    )

    def _get_deca_url_path(self):
        self.ensure_one()
        return "logistics_schedule_deca/deca"

    def _get_deca_document_name(self):
        self.ensure_one()
        return "Waybill_%s.pdf" % (self.name or self.id)

    def _check_deca_can_generate_extra(self):
        self.ensure_one()
        if not self.deca_driver_id:
            raise UserError(_(
                "You must set a driver before generating the DeCA document."
            ))
        if not self.deca_signature:
            raise UserError(_(
                "You must provide a signature before generating the DeCA document."
            ))

    def _get_deca_report(self):
        self.ensure_one()
        return self.env.ref('reports_alu.action_report_stock_picking_alumisel_waybill')

    def _generate_deca_document(self):
        self.ensure_one()
        report = self._get_deca_report()

        is_regeneration = bool(self.deca_is_generated)
        old_attachment = self.deca_attachment_id

        self.write({
            'deca_is_generated': True,
            'deca_generation_date': fields.Datetime.now(),
            'deca_generated_by_id': self.env.user.id,
        })
        self._compute_deca_data()
        pdf_content = self._render_deca_pdf(report)

        if not pdf_content:
            raise UserError(_("The DeCA document could not be rendered properly."))

        attachment = self.env['ir.attachment'].sudo().create({
            'name': self._get_deca_document_name(),
            'type': 'binary',
            'datas': base64.b64encode(pdf_content),
            'res_model': self._name,
            'res_id': self.id,
            'mimetype': 'application/pdf',
        })

        self.deca_attachment_id = attachment
        if old_attachment:
            old_attachment.sudo().unlink()

        message = (
            _(
                "DeCA document regenerated by %(user)s. New URL: %(url)s"
            ) if is_regeneration
            else _(
                "DeCA document generated by %(user)s. URL: %(url)s"
            )
        )
        self.message_post(body=(message % {'user': self.env.user.name, 'url': self.deca_url}))

        _logger.info("DeCA %s for %s record %s (%s)",
                    "regenerated" if is_regeneration else "generated",
                    self._name, self.display_name, self.deca_url)

    def _render_deca_pdf(self, report):
        self.ensure_one()
        Picking = self.env['stock.picking'].sudo()

        pdf_content = None
        try:
            with self.env.cr.savepoint():
                picking = Picking.create(self._build_deca_picking_vals())

                report_data = {}
                if hasattr(self, '_get_deca_base_report_values'):
                    report_data = self._get_deca_base_report_values()
                report_data['deca_sources'] = {picking.id: self}

                if hasattr(self, '_get_deca_report_data'):
                    extra_data = self._get_deca_report_data()
                    if extra_data:
                        report_data.update(extra_data)

                pdf_content, _report_type = self.env['ir.actions.report'].sudo()._render_qweb_pdf(
                    report.id, picking.ids, data=report_data
                )

                _logger.info(
                    "Temporary picking %s created to render the DeCA "
                    "document for logistics.schedule %s; it will be "
                    "rolled back and never persisted.",
                    picking.id, self.id,
                )
                raise _DiscardTemporaryPicking()
        except _DiscardTemporaryPicking:
            pass

        return pdf_content

    def _build_deca_picking_vals(self):
        self.ensure_one()

        picking_type = getattr(self.picking_id, 'picking_type_id', False)
        if not picking_type:
            picking_type = self.env['stock.picking.type'].search([
                ('code', '=', 'outgoing'),
                ('company_id', '=', self.company_id.id)
            ], limit=1)

        if not picking_type:
            raise UserError(_(
                "Cannot determine a picking type to generate the DeCA "
                "document for this schedule. Link it to a delivery order "
                "or configure a default picking type."
            ))

        partner_id = (
            getattr(self, 'destination_partner_id', False) and self.destination_partner_id.id
        ) or (
            getattr(self, 'partner_id', False) and self.partner_id.id
        )

        return {
            'partner_id': partner_id,
            'picking_type_id': picking_type.id,
            'location_id': picking_type.default_location_src_id.id,
            'location_dest_id': picking_type.default_location_dest_id.id,
            'company_id': self.company_id.id,
            'origin': getattr(self, 'origin', False) or getattr(self, 'name', False) or str(self.id),
            'scheduled_date': getattr(self, 'commitment_date', False) or fields.Datetime.now(),
            'date_done': getattr(self, 'effective_date', False) or fields.Datetime.now(),
            'note': getattr(self, 'note', False),
            'driver_id': self.deca_driver_id.id if self.deca_driver_id else False,
            'carrier_vehicle_id': getattr(self, 'carrier_id', False) and self.carrier_id.id or False,
            'towing_license_plate': getattr(self, 'license_plate_2', False) or False,
            'move_ids': [(0, 0, self._build_deca_move_vals(picking_type))],
        }

    def _build_deca_move_vals(self, picking_type):
        self.ensure_one()
        return {
            'name': self.product_id.display_name if self.product_id else _("DeCA Item"),
            'product_id': self.product_id.id,
            'product_uom_qty': getattr(self, 'product_uom_qty', 1.0),
            'quantity': getattr(self, 'product_uom_qty', 1.0),
            'product_uom': self.product_uom.id if getattr(self, 'product_uom', False) else False,
            'location_id': picking_type.default_location_src_id.id,
            'location_dest_id': picking_type.default_location_dest_id.id,
            'company_id': self.company_id.id,
        }
